baseurl = "https://collectingacorns.download/"
languageCode = "en-AU"
title = "I \u2764\ufe0f \U0001F330"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "chipmunk.gif"
  author = "Robert"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/social.css"]
  custom_js  = []

[params.social]
  Github        = "kochie"
  Email         = "hello@collectingacorns.download"
  Twitter       = "rkkochie"
  LinkedIn      = "rkkochie"
  Stackoverflow = "kochie"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "https://medium.com/@kochie"
[[menu.main]]
  name = "github"
  identifier = "github"
  weight = 200
  url = "https://github.com/kochie"
[[menu.main]]
  name = "me"
  identifier = "me"
  weight = 300
  url = "https://me.kochie.io"
